from verbecc.src.defs.types.conjugation import CompleteConjugation
from verbecc.src.defs.types.conjugation import CompleteConjugationData
from verbecc.src.defs.types.conjugation import Conjugation
from verbecc.src.defs.types.conjugation import ConjugationData
from verbecc.src.defs.types.conjugation import MoodConjugation
from verbecc.src.defs.types.conjugation import MoodConjugationData
from verbecc.src.defs.types.conjugation import MoodsConjugation
from verbecc.src.defs.types.conjugation import MoodsConjugationData
from verbecc.src.defs.types.conjugation import TenseConjugation
from verbecc.src.defs.types.conjugation import TenseConjugationData
from verbecc.src.defs.types.conjugation import VerbInfo
from verbecc.src.defs.types.conjugation import VerbInfoData
from verbecc.src.defs.types.data.conjugation_template import ConjugationTemplate
from verbecc.src.defs.types.data.conjugations import Conjugations
from verbecc.src.defs.types.data.element import Element
from verbecc.src.defs.types.data.mood_template import MoodTemplate
from verbecc.src.defs.types.data.person_ending import PersonEnding
from verbecc.src.defs.types.data.tense_template import TenseTemplate
from verbecc.src.defs.types.data.verb import Verb
from verbecc.src.defs.types.data.verbs import Verbs
from verbecc.src.defs.types.exceptions import ConjugationsParserError
from verbecc.src.defs.types.exceptions import ConjugationTemplateError
from verbecc.src.defs.types.exceptions import ConjugatorError
from verbecc.src.defs.types.exceptions import InvalidLangError
from verbecc.src.defs.types.exceptions import InvalidMoodError
from verbecc.src.defs.types.exceptions import InvalidTenseError
from verbecc.src.defs.types.exceptions import TemplateNotFoundError
from verbecc.src.defs.types.exceptions import VerbNotFoundError
from verbecc.src.defs.types.gender import Gender
from verbecc.src.defs.types.lang_code import LangCodeISO639_1
from verbecc.src.defs.types.lang_specific_options import LangSpecificOptions
from verbecc.src.defs.types.lang_specific_options import LangSpecificOptionsEs
from verbecc.src.defs.types.lang_specific_options import LangSpecificOptionsFactory
from verbecc.src.defs.types.lang_specific_options import VoseoOptions
from verbecc.src.defs.types.mood import Mood
from verbecc.src.defs.types.mood import MoodCa
from verbecc.src.defs.types.mood import MoodEs
from verbecc.src.defs.types.mood import MoodFr
from verbecc.src.defs.types.mood import MoodIt
from verbecc.src.defs.types.mood import MoodPt
from verbecc.src.defs.types.mood import MoodRo
from verbecc.src.defs.types.mood import Moods
from verbecc.src.defs.types.number import Number
from verbecc.src.defs.types.person import Person
from verbecc.src.defs.types.tense import Tense
from verbecc.src.defs.types.tense import TenseCa
from verbecc.src.defs.types.tense import TenseEs
from verbecc.src.defs.types.tense import TenseFr
from verbecc.src.defs.types.tense import TenseIt
from verbecc.src.defs.types.tense import TensePt
from verbecc.src.defs.types.tense import TenseRo
from verbecc.src.defs.types.tense import Tenses
