from verbecc.src.defs.types.tense.tense import Tense
from verbecc.src.defs.types.tense.tenses import Tenses
from verbecc.src.defs.types.tense.tense_factory import TenseFactory
from verbecc.src.defs.types.tense.lang.tense_ca import TenseCa
from verbecc.src.defs.types.tense.lang.tense_en import TenseEn
from verbecc.src.defs.types.tense.lang.tense_es import TenseEs
from verbecc.src.defs.types.tense.lang.tense_fr import TenseFr
from verbecc.src.defs.types.tense.lang.tense_it import TenseIt
from verbecc.src.defs.types.tense.lang.tense_pt import TensePt
from verbecc.src.defs.types.tense.lang.tense_ro import TenseRo
