import pytest
from lxml import etree
import json

from tests.common import assert_json_str_equal
from verbecc.src.conjugator.conjugator import Conjugator
from verbecc.src.defs.types.conjugation import Conjugation, TenseConjugation
from verbecc.src.defs.types.gender import Gender
from verbecc.src.defs.types.lang_code import LangCodeISO639_1 as Lang
from verbecc.src.defs.types.mood import Moods
from verbecc.src.defs.types.number import Number
from verbecc.src.defs.types.person import Person
from verbecc.src.defs.types.tense import Tenses
from verbecc.src.parsers.tense_template_parser import TenseTemplateParser


@pytest.fixture(scope="module")
def cg():
    cg = Conjugator(lang=Lang.ca)
    yield cg


def test_all_verbs_have_templates(cg):
    verbs = cg.get_verbs()
    assert len(verbs) == 8616
    template_names = cg.get_template_names()
    assert len(template_names) == 66
    missing_verbs = []
    missing_templates = set()
    for verb in verbs:
        if verb.template not in template_names:
            missing_templates.add(verb.template)
            missing_verbs.append(verb)
    assert len(missing_templates) == len(missing_verbs) == 0


def test_find_verb_by_infinitive(cg):
    v = cg.find_verb_by_infinitive("abandonar")
    assert v.infinitive == "abandonar"
    assert v.template == "cant:ar"


@pytest.mark.parametrize(
    "infinitive,mood,tense,expected_result",
    [
        (
            "ser",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo sóc"],
                ["tu ets"],
                ["ell és"],
                ["ella és"],
                ["nosaltres som"],
                ["vosaltres sou"],
                ["ells són"],
                ["elles són"],
            ],
        ),
        (
            "ser",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo era"],
                ["tu eres"],
                ["ell era"],
                ["ella era"],
                ["nosaltres érem"],
                ["vosaltres éreu"],
                ["ells eren"],
                ["elles eren"],
            ],
        ),
        (
            "ser",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo fui"],
                ["tu fores"],
                ["ell fou"],
                ["ella fou"],
                ["nosaltres fórem"],
                ["vosaltres fóreu"],
                ["ells foren"],
                ["elles foren"],
            ],
        ),
        (
            "ser",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo seré"],
                ["tu seràs"],
                ["ell serà"],
                ["ella serà"],
                ["nosaltres serem"],
                ["vosaltres sereu"],
                ["ells seran"],
                ["elles seran"],
            ],
        ),
        (
            "ser",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo sigui"],
                ["tu siguis"],
                ["ell sigui"],
                ["ella sigui"],
                ["nosaltres siguem"],
                ["vosaltres sigueu"],
                ["ells siguin"],
                ["elles siguin"],
            ],
        ),
        (
            "ser",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo fos"],
                ["tu fossis"],
                ["ell fos"],
                ["ella fos"],
                ["nosaltres fóssim"],
                ["vosaltres fóssiu"],
                ["ells fossin"],
                ["elles fossin"],
            ],
        ),
        (
            "ser",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo seria", "jo fora"],
                ["tu series", "tu fores"],
                ["ell seria", "ell fora"],
                ["ella seria", "ella fora"],
                ["nosaltres seríem", "nosaltres fórem"],
                ["vosaltres seríeu", "vosaltres fóreu"],
                ["ells serien", "ells foren"],
                ["elles serien", "elles foren"],
            ],
        ),
        (
            "ser",
            "imperatiu",
            "imperatiu-present",
            [["sigues"], ["sigui"], ["siguem"], ["sigueu"], ["siguin"]],
        ),
        (
            "parlar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo parlo"],
                ["tu parles"],
                ["ell parla"],
                ["ella parla"],
                ["nosaltres parlem"],
                ["vosaltres parleu"],
                ["ells parlen"],
                ["elles parlen"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo parlava"],
                ["tu parlaves"],
                ["ell parlava"],
                ["nosaltres parlàvem"],
                ["vosaltres parlàveu"],
                ["ells parlaven"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo parlí"],
                ["tu parlares"],
                ["ell parlà"],
                ["nosaltres parlàrem"],
                ["vosaltres parlàreu"],
                ["ells parlaren"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo parlaré"],
                ["tu parlaràs"],
                ["ell parlarà"],
                ["nosaltres parlarem"],
                ["vosaltres parlareu"],
                ["ells parlaran"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo parli"],
                ["tu parlis"],
                ["ell parli"],
                ["nosaltres parlem"],
                ["vosaltres parleu"],
                ["ells parlin"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo parlés"],
                ["tu parlessis"],
                ["ell parlés"],
                ["nosaltres parléssim"],
                ["vosaltres parléssiu"],
                ["ells parlessin"],
            ],
        ),
        (
            "parlar",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo parlaria"],
                ["tu parlaries"],
                ["ell parlaria"],
                ["nosaltres parlaríem"],
                ["vosaltres parlaríeu"],
                ["ells parlarien"],
            ],
        ),
        (
            "estar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo estic"],
                ["tu estàs"],
                ["ell està"],
                ["nosaltres estem"],
                ["vosaltres esteu"],
                ["ells estan"],
            ],
        ),
        (
            "estar",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo estava"],
                ["tu estaves"],
                ["ell estava"],
                ["nosaltres estàvem"],
                ["vosaltres estàveu"],
                ["ells estaven"],
            ],
        ),
        (
            "estar",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo estiguí"],
                ["tu estigueres"],
                ["ell estigué"],
                ["nosaltres estiguérem"],
                ["vosaltres estiguéreu"],
                ["ells estigueren"],
            ],
        ),
        (
            "estar",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo estaré"],
                ["tu estaràs"],
                ["ell estarà"],
                ["nosaltres estarem"],
                ["vosaltres estareu"],
                ["ells estaran"],
            ],
        ),
        (
            "estar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo estigui"],
                ["tu estiguis"],
                ["ell estigui"],
                ["nosaltres estiguem"],
                ["vosaltres estigueu"],
                ["ells estiguin"],
            ],
        ),
        (
            "estar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo estigués"],
                ["tu estiguessis"],
                ["ell estigués"],
                ["nosaltres estiguéssim"],
                ["vosaltres estiguéssiu"],
                ["ells estiguessin"],
            ],
        ),
        (
            "estar",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo estaria"],
                ["tu estaries"],
                ["ell estaria"],
                ["nosaltres estaríem"],
                ["vosaltres estaríeu"],
                ["ells estarien"],
            ],
        ),
        (
            "haver",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo he", "jo haig"],
                ["tu has"],
                ["ell ha"],
                ["nosaltres havem", "nosaltres hem"],
                ["vosaltres haveu", "vosaltres heu"],
                ["ells han"],
            ],
        ),
        (
            "haver",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo havia"],
                ["tu havies"],
                ["ell havia"],
                ["nosaltres havíem"],
                ["vosaltres havíeu"],
                ["ells havien"],
            ],
        ),
        (
            "haver",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo haguí"],
                ["tu hagueres"],
                ["ell hagué"],
                ["nosaltres haguérem"],
                ["vosaltres haguéreu"],
                ["ells hagueren"],
            ],
        ),
        (
            "haver",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo hauré"],
                ["tu hauràs"],
                ["ell haurà"],
                ["nosaltres haurem"],
                ["vosaltres haureu"],
                ["ells hauran"],
            ],
        ),
        (
            "haver",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo hauria", "jo haguera"],
                ["tu hauries", "tu hagueras"],
                ["ell hauria", "ell haguera"],
                ["nosaltres hauríem", "nosaltres haguérem"],
                ["vosaltres hauríeu", "vosaltres haguéreu"],
                ["ells haurien", "ells hagueren"],
            ],
        ),
        (
            "haver",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo hagi"],
                ["tu hagis"],
                ["ell hagi"],
                ["nosaltres hàgim", "nosaltres haguem"],
                ["vosaltres hàgiu", "vosaltres hagueu"],
                ["ells hagin"],
            ],
        ),
        (
            "tenir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo tinc"],
                ["tu tens"],
                ["ell té"],
                ["nosaltres tenim"],
                ["vosaltres teniu"],
                ["ells tenen"],
            ],
        ),
        (
            "fer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo faig"],
                ["tu fas"],
                ["ell fa"],
                ["nosaltres fem"],
                ["vosaltres feu"],
                ["ells fan"],
            ],
        ),
        (
            "fer",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo feia"],
                ["tu feies"],
                ["ell feia"],
                ["nosaltres fèiem"],
                ["vosaltres fèieu"],
                ["ells feien"],
            ],
        ),
        (
            "servir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo serveixo"],
                ["tu serveixes"],
                ["ell serveix"],
                ["nosaltres servim"],
                ["vosaltres serviu"],
                ["ells serveixen"],
            ],
        ),
        (
            "veure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo veig"],
                ["tu veus"],
                ["ell veu"],
                ["nosaltres veiem"],
                ["vosaltres veieu"],
                ["ells veuen"],
            ],
        ),
        (
            "abandonar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo abandono"],
                ["tu abandones"],
                ["ell abandona"],
                ["nosaltres abandonem"],
                ["vosaltres abandoneu"],
                ["ells abandonen"],
            ],
        ),
        (
            "rebre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo rebo"],
                ["tu reps"],
                ["ell rep"],
                ["nosaltres rebem"],
                ["vosaltres rebeu"],
                ["ells reben"],
            ],
        ),
        (
            "cabre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo cabo"],
                ["tu caps"],
                ["ell cap"],
                ["nosaltres cabem"],
                ["vosaltres cabeu"],
                ["ells caben"],
            ],
        ),
        (
            "començar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo començo"],
                ["tu comences"],
                ["ell comença"],
                ["nosaltres comencem"],
                ["vosaltres comenceu"],
                ["ells comencen"],
            ],
        ),
        (
            "enaiguar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo enaiguo"],
                ["tu enaigües"],
                ["ell enaigua"],
                ["nosaltres enaigüem"],
                ["vosaltres enaigüeu"],
                ["ells enaigüen"],
            ],
        ),
        (
            "envejar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo envejo"],
                ["tu enveges"],
                ["ell enveja"],
                ["nosaltres envegem"],
                ["vosaltres envegeu"],
                ["ells envegen"],
            ],
        ),
        (
            "esglaiar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo esglaio"],
                ["tu esglaies"],
                ["ell esglaia"],
                ["nosaltres esglaiem"],
                ["vosaltres esglaieu"],
                ["ells esglaien"],
            ],
        ),
        (
            "trencar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo trenco"],
                ["tu trenques"],
                ["ell trenca"],
                ["nosaltres trenquem"],
                ["vosaltres trenqueu"],
                ["ells trenquen"],
            ],
        ),
        (
            "perdre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo perdo"],
                ["tu perds"],
                ["ell perd"],
                ["nosaltres perdem"],
                ["vosaltres perdeu"],
                ["ells perden"],
            ],
        ),
        (
            "caure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo caic"],
                ["tu caus"],
                ["ell cau"],
                ["nosaltres caiem"],
                ["vosaltres caieu"],
                ["ells cauen"],
            ],
        ),
        (
            "collar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo collo"],
                ["tu colles"],
                ["ell colla"],
                ["nosaltres collem"],
                ["vosaltres colleu"],
                ["ells collen"],
            ],
        ),
        (
            "collir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo cullo"],
                ["tu culls"],
                ["ell cull"],
                ["nosaltres collim"],
                ["vosaltres colliu"],
                ["ells cullen"],
            ],
        ),
        (
            "dormir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo dormo"],
                ["tu dorms"],
                ["ell dorm"],
                ["nosaltres dormim"],
                ["vosaltres dormiu"],
                ["ells dormen"],
            ],
        ),
        (
            "tossir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo tusso"],
                ["tu tusses"],
                ["ell tus"],
                ["nosaltres tossim"],
                ["vosaltres tossiu"],
                ["ells tussen"],
            ],
        ),
        (
            "collir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo culli"],
                ["tu cullis"],
                ["ell culli"],
                ["nosaltres collim"],
                ["vosaltres colliu"],
                ["ells cullin"],
            ],
        ),
        (
            "dormir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo dormi"],
                ["tu dormis"],
                ["ell dormi"],
                ["nosaltres dormim"],
                ["vosaltres dormiu"],
                ["ells dormin"],
            ],
        ),
        (
            "tossir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo tussi"],
                ["tu tussis"],
                ["ell tussi"],
                ["nosaltres tossim"],
                ["vosaltres tossiu"],
                ["ells tussin"],
            ],
        ),
        (
            "dir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo dic"],
                ["tu dius"],
                ["ell diu"],
                ["nosaltres diem"],
                ["vosaltres dieu"],
                ["ells diuen"],
            ],
        ),
        (
            "anar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo vaig"],
                ["tu vas"],
                ["ell va"],
                ["nosaltres anem"],
                ["vosaltres aneu"],
                ["ells van"],
            ],
        ),
        (
            "poder",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo puc"],
                ["tu pots"],
                ["ell pot"],
                ["nosaltres podem"],
                ["vosaltres podeu"],
                ["ells poden"],
            ],
        ),
        (
            "arribar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo arribo"],
                ["tu arribes"],
                ["ell arriba"],
                ["nosaltres arribem"],
                ["vosaltres arribeu"],
                ["ells arriben"],
            ],
        ),
        (
            "trobar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo trobo"],
                ["tu trobes"],
                ["ell troba"],
                ["nosaltres trobem"],
                ["vosaltres trobeu"],
                ["ells troben"],
            ],
        ),
        (
            "partir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo parteixo"],
                ["tu parteixes"],
                ["ell parteix"],
                ["nosaltres partim"],
                ["vosaltres partiu"],
                ["ells parteixen"],
            ],
        ),
        (
            "morir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo moro"],
                ["tu mors"],
                ["ell mor"],
                ["nosaltres morim"],
                ["vosaltres moriu"],
                ["ells moren"],
            ],
        ),
        (
            "eixir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo ixo", "jo isc"],
                ["tu ixes"],
                ["ell ix"],
                ["nosaltres eixim"],
                ["vosaltres eixiu"],
                ["ells ixen"],
            ],
        ),
        (
            "jaure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo jec"],
                ["tu jeus"],
                ["ell jeu"],
                ["nosaltres jaiem"],
                ["vosaltres jaieu"],
                ["ells jeuen"],
            ],
        ),
        (
            "jeure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo jec"],
                ["tu jeus"],
                ["ell jeu"],
                ["nosaltres jaiem"],
                ["vosaltres jaieu"],
                ["ells jeuen"],
            ],
        ),
        (
            "pagar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo pago"],
                ["tu pagues"],
                ["ell paga"],
                ["nosaltres paguem"],
                ["vosaltres pagueu"],
                ["ells paguen"],
            ],
        ),
        (
            "mentir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo menteixo", "jo mento"],
                ["tu menteixes", "tu ments"],
                ["ell menteix", "ell ment"],
                ["nosaltres mentim"],
                ["vosaltres mentiu"],
                ["ells menteixen", "ells menten"],
            ],
        ),
        (
            "desmentir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo desmenteixo", "jo desmento"],
                ["tu desmenteixes", "tu desments"],
                ["ell desmenteix", "ell desment"],
                ["nosaltres desmentim"],
                ["vosaltres desmentiu"],
                ["ells desmenteixen", "ells desmenten"],
            ],
        ),
        (
            "nàixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo naixo", "jo neixo"],
                ["tu naixes", "tu neixes"],
                ["ell naix", "ell neix"],
                ["nosaltres naixem"],
                ["vosaltres naixeu"],
                ["ells naixen", "ells neixen"],
            ],
        ),
        (
            "néixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo naixo", "jo neixo"],
                ["tu naixes", "tu neixes"],
                ["ell naix", "ell neix"],
                ["nosaltres naixem"],
                ["vosaltres naixeu"],
                ["ells naixen", "ells neixen"],
            ],
        ),
        (
            "obrir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo obro"],
                ["tu obres"],
                ["ell obre"],
                ["nosaltres obrim"],
                ["vosaltres obriu"],
                ["ells obren"],
            ],
        ),
        (
            "riure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo ric"],
                ["tu rius"],
                ["ell riu"],
                ["nosaltres riem"],
                ["vosaltres rieu"],
                ["ells riuen"],
            ],
        ),
        (
            "pertànyer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo pertanyo"],
                ["tu pertanys"],
                ["ell pertany"],
                ["nosaltres pertanyem"],
                ["vosaltres pertanyeu"],
                ["ells pertanyen"],
            ],
        ),
        (
            "pertànyer",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo pertanyí", "jo pertanguí"],
                ["tu pertanyeres", "tu pertangueres"],
                ["ell pertanyé", "ell pertangué"],
                ["nosaltres pertanyérem", "nosaltres pertanguérem"],
                ["vosaltres pertanyéreu", "vosaltres pertanguéreu"],
                ["ells pertanyeren", "ells pertanguéren"],
            ],
        ),
        (
            "fènyer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo fenyo"],
                ["tu fenys"],
                ["ell feny"],
                ["nosaltres fenyem"],
                ["vosaltres fenyeu"],
                ["ells fenyen"],
            ],
        ),
        (
            "córrer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo corro"],
                ["tu corres"],
                ["ell corre"],
                ["nosaltres correm"],
                ["vosaltres correu"],
                ["ells corren"],
            ],
        ),
        (
            "transcórrer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo transcorro"],
                ["tu transcorres"],
                ["ell transcorre"],
                ["nosaltres transcorrem"],
                ["vosaltres transcorreu"],
                ["ells transcorren"],
            ],
        ),
        (
            "imprimir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo imprimeixo"],
                ["tu imprimeixes"],
                ["ell imprimeix"],
                ["nosaltres imprimim"],
                ["vosaltres imprimiu"],
                ["ells imprimeixen"],
            ],
        ),
        (
            "imprimir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo imprimeixo"],
                ["tu imprimeixes"],
                ["ella imprimeix"],
                ["nosaltres imprimim"],
                ["vosaltres imprimiu"],
                ["elles imprimeixen"],
            ],
        ),
        (
            "vindre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo vindo"],
                ["tu vinds"],
                ["ella vind"],
                ["nosaltres vindem"],
                ["vosaltres vindeu"],
                ["elles vinden"],
            ],
        ),
        (
            "tòrcer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo torço"],
                ["tu torces"],
                ["ella torça"],
                ["nosaltres torcem"],
                ["vosaltres torceu"],
                ["elles torcen"],
            ],
        ),
        (
            "caldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["-"],
                ["-"],
                ["ella cal"],
                ["-"],
                ["-"],
                ["elles calen"],
            ],
        ),
        (
            "obeir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo obeeixo"],
                ["tu obeeixes"],
                ["ella obeeix"],
                ["nosaltres obeïm"],
                ["vosaltres obeïu"],
                ["elles obeeixen"],
            ],
        ),
        (
            "beneir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo beneeixo"],
                ["tu beneeixes"],
                ["ella beneeix"],
                ["nosaltres beneïm"],
                ["vosaltres beneïu"],
                ["elles beneeixen"],
            ],
        ),
        (
            "coldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo colc"],
                ["tu cols"],
                ["ella col"],
                ["nosaltres colem"],
                ["vosaltres coleu"],
                ["elles colen"],
            ],
        ),
        (
            "dissoldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo dissolc"],
                ["tu dissols"],
                ["ella dissol"],
                ["nosaltres dissolem"],
                ["vosaltres dissoleu"],
                ["elles dissolen"],
            ],
        ),
        (
            "percudir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo percudeixo", "jo percudo"],
                ["tu percudeixes", "tu percuts"],
                ["ella percudeix", "ella percut"],
                ["nosaltres percudim"],
                ["vosaltres percudiu"],
                ["elles percudeixen", "elles percuden"],
            ],
        ),
        (
            "permetre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo permeto"],
                ["tu permets"],
                ["ella permet"],
                ["nosaltres permetem"],
                ["vosaltres permeteu"],
                ["elles permeten"],
            ],
        ),
        (
            "desconèixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo desconec"],
                ["tu desconeixes"],
                ["ella desconeix"],
                ["nosaltres desconeixem"],
                ["vosaltres desconeixeu"],
                ["elles desconeixen"],
            ],
        ),
        (
            "desconèixer",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo desconeguí"],
                ["tu desconegueres"],
                ["ella desconegué"],
                ["nosaltres desconeguérem"],
                ["vosaltres desconeguéreu"],
                ["elles desconegueren"],
            ],
        ),
        (
            "parèixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo parec"],
                ["tu pareixes"],
                ["ella pareix"],
                ["nosaltres pareixem"],
                ["vosaltres pareixeu"],
                ["elles pareixen"],
            ],
        ),
        (
            "expendre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo expenc"],
                ["tu expens"],
                ["ella expèn"],
                ["nosaltres expenem"],
                ["vosaltres expeneu"],
                ["elles expenen"],
            ],
        ),
        (
            "contendre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo contenc"],
                ["tu contens"],
                ["ella contén"],
                ["nosaltres contenem"],
                ["vosaltres conteneu"],
                ["elles contenen"],
            ],
        ),
        (
            "atènyer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo atenyo"],
                ["tu atenys"],
                ["ella ateny"],
                ["nosaltres atenyem"],
                ["vosaltres atenyeu"],
                ["elles atenyen"],
            ],
        ),
        (
            "descloure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo descloc"],
                ["tu desclous"],
                ["ella desclou"],
                ["nosaltres descloem"],
                ["vosaltres descloeu"],
                ["elles desclouen"],
            ],
        ),
        (
            "descloure",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["desclòs"], ["desclosa"], ["desclosos"], ["descloses"]],
        ),
        (
            "cloure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo cloc"],
                ["tu clous"],
                ["ella clou"],
                ["nosaltres cloem"],
                ["vosaltres cloeu"],
                ["elles clouen"],
            ],
        ),
        (
            "abreviar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo abrevio"],
                ["tu abrevies"],
                ["ella abrevia"],
                ["nosaltres abreviem"],
                ["vosaltres abrevieu"],
                ["elles abrevien"],
            ],
        ),
        (
            "abreviar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo abreviï"],
                ["tu abreviïs"],
                ["ella abreviï"],
                ["nosaltres abreviem"],
                ["vosaltres abrevieu"],
                ["elles abreviïn"],
            ],
        ),
        (
            "abreviar",
            "imperatiu",
            "imperatiu-present",
            [["abrevia"], ["abreviï"], ["abreviem"], ["abrevieu"], ["abreviïn"]],
        ),
        (
            "compondre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo componc"],
                ["tu compons"],
                ["ella compon"],
                ["nosaltres componem"],
                ["vosaltres componeu"],
                ["elles componen"],
            ],
        ),
        (
            "contendre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo contenc"],
                ["tu contens"],
                ["ella contén"],
                ["nosaltres contenem"],
                ["vosaltres conteneu"],
                ["elles contenen"],
            ],
        ),
        (
            "complir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo compleixo"],
                ["tu compleixes"],
                ["ella compleix"],
                ["nosaltres complim"],
                ["vosaltres compliu"],
                ["elles compleixen"],
            ],
        ),
        (
            "establir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo estableixo"],
                ["tu estableixes"],
                ["ella estableix"],
                ["nosaltres establim"],
                ["vosaltres establiu"],
                ["elles estableixen"],
            ],
        ),
        (
            "complaure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo complac"],
                ["tu complaus"],
                ["ella complau"],
                ["nosaltres complaem"],
                ["vosaltres complaeu"],
                ["elles complauen"],
            ],
        ),
        (
            "desplaure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo desplac"],
                ["tu desplaus"],
                ["ella desplau"],
                ["nosaltres desplaem"],
                ["vosaltres desplaeu"],
                ["elles desplauen"],
            ],
        ),
        (
            "complaure",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["complagut"], ["complaguda"], ["complaguts"], ["complagudes"]],
        ),
        (
            "acréixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo acreixo"],
                ["tu acreixes"],
                ["ella acreix"],
                ["nosaltres acreixem"],
                ["vosaltres acreixeu"],
                ["elles acreixen"],
            ],
        ),
        (
            "acréixer",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo acreixí", "jo acresquí"],
                ["tu acreixeres", "tu acresqueres"],
                ["ella acreixé", "ella acresqué"],
                ["nosaltres acreixérem", "nosaltres acresquérem"],
                ["vosaltres acreixéreu", "vosaltres acresquéreu"],
                ["elles acreixeren", "elles acresqueren"],
            ],
        ),
        (
            "acréixer",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo acreixés", "jo acresqués"],
                ["tu acreixessis", "tu acresquessis"],
                ["ella acreixés", "ella acresqués"],
                ["nosaltres acreixéssim", "nosaltres acresquéssim"],
                ["vosaltres acreixéssiu", "vosaltres acresquéssiu"],
                ["elles acreixessin", "elles acresquessin"],
            ],
        ),
        (
            "merèixer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo mereixo"],
                ["tu mereixes"],
                ["ella mereix"],
                ["nosaltres mereixem"],
                ["vosaltres mereixeu"],
                ["elles mereixen"],
            ],
        ),
        (
            "confondre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo confonc"],
                ["tu confons"],
                ["ella confon"],
                ["nosaltres confonem"],
                ["vosaltres confoneu"],
                ["elles confonen"],
            ],
        ),
        (
            "consternar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo consterno"],
                ["tu consternes"],
                ["ella consterna"],
                ["nosaltres consternem"],
                ["vosaltres consterneu"],
                ["elles consternen"],
            ],
        ),
        (
            "contradir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo contradic"],
                ["tu contradius"],
                ["ella contradiu"],
                ["nosaltres contradiem"],
                ["vosaltres contradieu"],
                ["elles contradiuen"],
            ],
        ),
        (
            "contradir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["contradit"], ["contradida"], ["contradits"], ["contradides"]],
        ),
        (
            "dir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["dit"], ["dita"], ["dits"], ["dites"]],
        ),
        (
            "creure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo crec"],
                ["tu creus"],
                ["ella creu"],
                ["nosaltres creiem"],
                ["vosaltres creieu"],
                ["elles creuen"],
            ],
        ),
        (
            "creure",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo creuré"],
                ["tu creuràs"],
                ["ella creurà"],
                ["nosaltres creurem"],
                ["vosaltres creureu"],
                ["elles creuran"],
            ],
        ),
        (
            "dur",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo duc"],
                ["tu duus", "tu dus"],
                ["ella duu", "ella du"],
                ["nosaltres duem"],
                ["vosaltres dueu"],
                ["elles duen"],
            ],
        ),
        (
            "dur",
            "imperatiu",
            "imperatiu-present",
            [["duu", "du"], ["dugui"], ["duguem"], ["dueu"], ["duguin"]],
        ),
        (
            "descosir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo descuso"],
                ["tu descuses"],
                ["ella descús"],
                ["nosaltres descosim"],
                ["vosaltres descosiu"],
                ["elles descusen"],
            ],
        ),
        (
            "descosir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo descusi"],
                ["tu descusis"],
                ["ella descusi"],
                ["nosaltres descosim"],
                ["vosaltres descosiu"],
                ["elles descusin"],
            ],
        ),
        (
            "descosir",
            "imperatiu",
            "imperatiu-present",
            [["descús"], ["descusi"], ["descosim"], ["descosiu"], ["descusin"]],
        ),
        (
            "valer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo valc"],
                ["tu vals"],
                ["ella val"],
                ["nosaltres valem"],
                ["vosaltres valeu"],
                ["elles valen"],
            ],
        ),
        (
            "valer",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo valguí"],
                ["tu valgueres"],
                ["ella valgué"],
                ["nosaltres valguérem"],
                ["vosaltres valguéreu"],
                ["elles valgueren"],
            ],
        ),
        (
            "doldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo dolc"],
                ["tu dols"],
                ["ella dol"],
                ["nosaltres dolem"],
                ["vosaltres doleu"],
                ["elles dolen"],
            ],
        ),
        (
            "entrelluir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo entrelluo"],
                ["tu entrelluus"],
                ["ell entrelluu", "ell entrellú"],
                ["nosaltres entrelluïm"],
                ["vosaltres entrelluïu"],
                ["ells entrelluen"],
            ],
        ),
        (
            "entrelluir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo entrelluo"],
                ["tu entrelluus"],
                ["ella entrelluu", "ella entrellú"],
                ["nosaltres entrelluïm"],
                ["vosaltres entrelluïu"],
                ["elles entrelluen"],
            ],
        ),
        (
            "entrelluir",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo entrelluïa"],
                ["tu entrelluïes"],
                ["ella entrelluïa"],
                ["nosaltres entrelluíem"],
                ["vosaltres entrelluíeu"],
                ["elles entrelluïen"],
            ],
        ),
        (
            "entrelluir",
            "imperatiu",
            "imperatiu-present",
            [
                ["entrelluu", "entrellú"],
                ["entrelluï"],
                ["entrelluïm"],
                ["entrelluïu"],
                ["entrelluïn"],
            ],
        ),
        (
            "esglaiar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo esglaio"],
                ["tu esglaies"],
                ["ella esglaia"],
                ["nosaltres esglaiem"],
                ["vosaltres esglaieu"],
                ["elles esglaien"],
            ],
        ),
        (
            "esglaiar",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo esglaí"],
                ["tu esglaiares"],
                ["ella esglaià"],
                ["nosaltres esglaiàrem"],
                ["vosaltres esglaiàreu"],
                ["elles esglaiaren"],
            ],
        ),
        (
            "esglaiar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo esglaï"],
                ["tu esglaïs"],
                ["ella esglaï"],
                ["nosaltres esglaiem"],
                ["vosaltres esglaieu"],
                ["elles esglaïn"],
            ],
        ),
        (
            "esglaiar",
            "imperatiu",
            "imperatiu-present",
            [["esglaia"], ["esglaï"], ["esglaiem"], ["esglaieu"], ["esglaïn"]],
        ),
        (
            "esglaiar",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["esglaiat"], ["esglaiada"], ["esglaiats"], ["esglaiades"]],
        ),
        (
            "evacuar",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo evacuo"],
                ["tu evacues"],
                ["ella evacua"],
                ["nosaltres evacuem"],
                ["vosaltres evacueu"],
                ["elles evacuen"],
            ],
        ),
        (
            "evacuar",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo evacuï"],
                ["tu evacuïs"],
                ["ella evacuï"],
                ["nosaltres evacuem"],
                ["vosaltres evacueu"],
                ["elles evacuïn"],
            ],
        ),
        (
            "evacuar",
            "imperatiu",
            "imperatiu-present",
            [["evacua"], ["evacuï"], ["evacuem"], ["evacueu"], ["evacuïn"]],
        ),
        (
            "tondre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo tonc"],
                ["tu tons"],
                ["ella ton"],
                ["nosaltres tonem"],
                ["vosaltres toneu"],
                ["elles tonen"],
            ],
        ),
        (
            "fugir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo fujo"],
                ["tu fuges"],
                ["ella fuig"],
                ["nosaltres fugim"],
                ["vosaltres fugiu"],
                ["elles fugen"],
            ],
        ),
        (
            "fugir",
            "imperatiu",
            "imperatiu-present",
            [["fuig"], ["fugi"], ["fugim"], ["fugiu"], ["fugin"]],
        ),
        (
            "imprimir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo imprimeixo"],
                ["tu imprimeixes"],
                ["ella imprimeix"],
                ["nosaltres imprimim"],
                ["vosaltres imprimiu"],
                ["elles imprimeixen"],
            ],
        ),
        (
            "imprimir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["imprès"], ["impresa"], ["impresos"], ["impreses"]],
        ),
        (
            "ajeure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo ajec"],
                ["tu ajeus"],
                ["ella ajeu"],
                ["nosaltres ajaiem"],
                ["vosaltres ajaieu"],
                ["elles ajeuen"],
            ],
        ),
        (
            "moldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo molc"],
                ["tu mols"],
                ["ella mol"],
                ["nosaltres molem"],
                ["vosaltres moleu"],
                ["elles molen"],
            ],
        ),
        (
            "malvendre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo malvenc"],
                ["tu malvens"],
                ["ella malvèn"],
                ["nosaltres malvenem"],
                ["vosaltres malveneu"],
                ["elles malvenen"],
            ],
        ),
        (
            "malvendre",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo malvenia"],
                ["tu malvenies"],
                ["ella malvenia"],
                ["nosaltres malveníem"],
                ["vosaltres malveníeu"],
                ["elles malvenien"],
            ],
        ),
        (
            "malvendre",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo malvenguí"],
                ["tu malvengueres"],
                ["ella malvengué"],
                ["nosaltres malvenguérem"],
                ["vosaltres malvenguéreu"],
                ["elles malvengueren"],
            ],
        ),
        (
            "malvendre",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo malvengui"],
                ["tu malvenguis"],
                ["ella malvengui"],
                ["nosaltres malvenguem"],
                ["vosaltres malvengueu"],
                ["elles malvenguin"],
            ],
        ),
        (
            "malvendre",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo malvengués"],
                ["tu malvenguessis"],
                ["ella malvengués"],
                ["nosaltres malvenguéssim"],
                ["vosaltres malvenguéssiu"],
                ["elles malvenguessin"],
            ],
        ),
        (
            "omplir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo omplo"],
                ["tu omples"],
                ["ella omple"],
                ["nosaltres omplim"],
                ["vosaltres ompliu"],
                ["elles omplen"],
            ],
        ),
        (
            "omplir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [
                ["omplert", "omplit"],
                ["omplerta", "omplida"],
                ["omplerts", "omplits"],
                ["omplertes", "omplides"],
            ],
        ),
        (
            "omplir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [
                ["omplert", "omplit"],
                ["omplerta", "omplida"],
                ["omplerts", "omplits"],
                ["omplertes", "omplides"],
            ],
        ),
        (
            "omplir",
            "imperatiu",
            "imperatiu-present",
            [["omple"], ["ompli"], ["omplim"], ["ompliu"], ["omplin"]],
        ),
        (
            "moure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo moc"],
                ["tu mous"],
                ["ella mou"],
                ["nosaltres movem"],
                ["vosaltres moveu"],
                ["elles mouen"],
            ],
        ),
        (
            "moure",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo moguí"],
                ["tu mogueres"],
                ["ella mogué"],
                ["nosaltres moguérem"],
                ["vosaltres moguéreu"],
                ["elles mogueren"],
            ],
        ),
        (
            "moure",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo movia"],
                ["tu movies"],
                ["ella movia"],
                ["nosaltres movíem"],
                ["vosaltres movíeu"],
                ["elles movien"],
            ],
        ),
        (
            "absoldre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo absolc"],
                ["tu absols"],
                ["ella absol"],
                ["nosaltres absolem"],
                ["vosaltres absoleu"],
                ["elles absolen"],
            ],
        ),
        (
            "absoldre",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["absolt"], ["absolta"], ["absolts"], ["absoltes"]],
        ),
        (
            "obrir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo obro"],
                ["tu obres"],
                ["ella obre"],
                ["nosaltres obrim"],
                ["vosaltres obriu"],
                ["elles obren"],
            ],
        ),
        (
            "obrir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["obert"], ["oberta"], ["oberts"], ["obertes"]],
        ),
        (
            "prevenir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo previnc"],
                ["tu prevens"],
                ["ella prevé"],
                ["nosaltres prevenim"],
                ["vosaltres preveniu"],
                ["elles prevenen"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo previnguí"],
                ["tu previngueres"],
                ["ella previngué"],
                ["nosaltres previnguérem"],
                ["vosaltres previnguéreu"],
                ["elles previngueren"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo prevenia"],
                ["tu prevenies"],
                ["ella prevenia"],
                ["nosaltres preveníem"],
                ["vosaltres preveníeu"],
                ["elles prevenien"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo previndré"],
                ["tu previndràs"],
                ["ella previndrà"],
                ["nosaltres previndrem"],
                ["vosaltres previndreu"],
                ["elles previndran"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo previngui"],
                ["tu previnguis"],
                ["ella previngui"],
                ["nosaltres previnguem"],
                ["vosaltres previngueu"],
                ["elles previnguin"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo previngués"],
                ["tu previnguessis"],
                ["ell previngués"],
                ["ella previngués"],
                ["nosaltres previnguéssim"],
                ["vosaltres previnguéssiu"],
                ["ells previnguessin"],
                ["elles previnguessin"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo previndria"],
                ["tu previndries"],
                ["ell previndria"],
                ["ella previndria"],
                ["nosaltres previndríem"],
                ["vosaltres previndríeu"],
                ["ells previndrien"],
                ["elles previndrien"],
            ],
        ),
        (
            "prevenir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["previngut"], ["previnguda"], ["previnguts"], ["previngudes"]],
        ),
        (
            "prevenir",
            "imperatiu",
            "imperatiu-present",
            [["prevén"], ["previngui"], ["previnguem"], ["preveniu"], ["previnguin"]],
        ),
        (
            "sortir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo surto"],
                ["tu surts"],
                ["ell surt"],
                ["ella surt"],
                ["nosaltres sortim"],
                ["vosaltres sortiu"],
                ["ells surten"],
                ["elles surten"],
            ],
        ),
        (
            "sortir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo surti"],
                ["tu surtis"],
                ["ell surti"],
                ["ella surti"],
                ["nosaltres sortim"],
                ["vosaltres sortiu"],
                ["ells surtin"],
                ["elles surtin"],
            ],
        ),
        (
            "sortir",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["sortit"], ["sortida"], ["sortits"], ["sortides"]],
        ),
        (
            "sortir",
            "imperatiu",
            "imperatiu-present",
            [["surt"], ["surti"], ["sortim"], ["sortiu"], ["surtin"]],
        ),
        (
            "témer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo temo"],
                ["tu tems"],
                ["ell tem"],
                ["ella tem"],
                ["nosaltres temem"],
                ["vosaltres temeu"],
                ["ells temen"],
                ["elles temen"],
            ],
        ),
        (
            "témer",
            "infinitiu",
            "infinitiu-present",
            [["témer"]],
        ),
        (
            "témer",
            "gerundi",
            "gerundi",
            [["tement"]],
        ),
        (
            "témer",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["temut"], ["temuda"], ["temuts"], ["temudes"]],
        ),
        (
            "retraure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo retrec"],
                ["tu retreus"],
                ["ell retreu"],
                ["ella retreu"],
                ["nosaltres retraiem"],
                ["vosaltres retraieu"],
                ["ells retreuen"],
                ["elles retreuen"],
            ],
        ),
        (
            "retraure",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo retreia"],
                ["tu retreies"],
                ["ell retreia"],
                ["ella retreia"],
                ["nosaltres retrèiem"],
                ["vosaltres retrèieu"],
                ["ells retreien"],
                ["elles retreien"],
            ],
        ),
        (
            "retraure",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo retraguí"],
                ["tu retragueres"],
                ["ell retragué"],
                ["ella retragué"],
                ["nosaltres retraguérem"],
                ["vosaltres retraguéreu"],
                ["ells retragueren"],
                ["elles retragueren"],
            ],
        ),
        (
            "retraure",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo retraué"],
                ["tu retrauàs"],
                ["ell retrauà"],
                ["ella retrauà"],
                ["nosaltres retrauem"],
                ["vosaltres retraueu"],
                ["ells retrauan"],
                ["elles retrauan"],
            ],
        ),
        (
            "retraure",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo retrauia"],
                ["tu retrauies"],
                ["ell retrauia"],
                ["ella retrauia"],
                ["nosaltres retrauíem"],
                ["vosaltres retrauíeu"],
                ["ells retrauien"],
                ["elles retrauien"],
            ],
        ),
        (
            "retraure",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo retregui"],
                ["tu retreguis"],
                ["ell retregui"],
                ["ella retregui"],
                ["nosaltres retreguem"],
                ["vosaltres retregueu"],
                ["ells retreguin"],
                ["elles retreguin"],
            ],
        ),
        (
            "premorir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo premoro"],
                ["tu premors"],
                ["ella premor"],
                ["nosaltres premorim"],
                ["vosaltres premoriu"],
                ["elles premoren"],
            ],
        ),
        (
            "conviure",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo convisc"],
                ["tu convius"],
                ["ella conviu"],
                ["nosaltres convivim"],
                ["vosaltres conviviu"],
                ["elles conviuen"],
            ],
        ),
        (
            "conviure",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo convivia"],
                ["tu convivies"],
                ["ella convivia"],
                ["nosaltres convivíem"],
                ["vosaltres convivíeu"],
                ["elles convivien"],
            ],
        ),
        (
            "conviure",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo convisquí"],
                ["tu convisqueres"],
                ["ella convisqué"],
                ["nosaltres convisquérem"],
                ["vosaltres convisquéreu"],
                ["elles convisqueren"],
            ],
        ),
        (
            "vèncer",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo venço"],
                ["tu vences"],
                ["ella venç"],
                ["nosaltres vencem"],
                ["vosaltres venceu"],
                ["elles vencen"],
            ],
        ),
        (
            "vèncer",
            "imperatiu",
            "imperatiu-present",
            [["venç"], ["venci"], ["vencem"], ["venceu"], ["vencin"]],
        ),
        (
            "vèncer",
            Moods.ca.Participi,
            Tenses.ca.Participi,
            [["vençut"], ["vençuda"], ["vençuts"], ["vençudes"]],
        ),
        (
            "vèncer",
            "infinitiu",
            "infinitiu-present",
            [["vèncer"]],
        ),
        (
            "vèncer",
            "gerundi",
            "gerundi",
            [["vencent"]],
        ),
        (
            "cerndre",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo cerno"],
                ["tu cerns"],
                ["ella cern"],
                ["nosaltres cernem"],
                ["vosaltres cerneu"],
                ["elles cernen"],
            ],
        ),
        (
            "oir",
            Moods.ca.Indicatiu,
            Tenses.ca.Present,
            [
                ["jo oeixo"],
                ["tu oeixes"],
                ["ella oeix"],
                ["nosaltres oïm"],
                ["vosaltres oïu"],
                ["elles oeixen"],
            ],
        ),
        (
            "oir",
            Moods.ca.Indicatiu,
            Tenses.ca.Imperfet,
            [
                ["jo oïa"],
                ["tu oïes"],
                ["ella oïa"],
                ["nosaltres oíem"],
                ["vosaltres oíeu"],
                ["elles oïen"],
            ],
        ),
        (
            "oir",
            Moods.ca.Indicatiu,
            Tenses.ca.PassatSimple,
            [
                ["jo oí"],
                ["tu oïres"],
                ["ella oí"],
                ["nosaltres oírem"],
                ["vosaltres oíreu"],
                ["elles oïren"],
            ],
        ),
        (
            "oir",
            Moods.ca.Indicatiu,
            Tenses.ca.Futur,
            [
                ["jo oiré"],
                ["tu oiràs"],
                ["ella oirà"],
                ["nosaltres oirem"],
                ["vosaltres oireu"],
                ["elles oiran"],
            ],
        ),
        (
            "oir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Present,
            [
                ["jo oeixi"],
                ["tu oeixis"],
                ["ella oeixi"],
                ["nosaltres oïm"],
                ["vosaltres oïu"],
                ["elles oeixin"],
            ],
        ),
        (
            "oir",
            Moods.ca.Subjuntiu,
            Tenses.ca.Imperfet,
            [
                ["jo oís"],
                ["tu oïssis"],
                ["ella oís"],
                ["nosaltres oíssim"],
                ["vosaltres oíssiu"],
                ["elles oïssin"],
            ],
        ),
        (
            "oir",
            Moods.ca.Condicional,
            Tenses.ca.Present,
            [
                ["jo oiria"],
                ["tu oiries"],
                ["ella oiria"],
                ["nosaltres oiríem"],
                ["vosaltres oiríeu"],
                ["elles oirien"],
            ],
        ),
        (
            "oir",
            Moods.ca.Participi,
            Moods.ca.Participi,
            [["oït"], ["oïda"], ["oïts"], ["oïdes"]],
        ),
        (
            "oir",
            "infinitiu",
            "infinitiu-present",
            [["oir"]],
        ),
        (
            "oir",
            "gerundi",
            "gerundi",
            [["oint"]],
        ),
        (
            "oir",
            "imperatiu",
            "imperatiu-present",
            [["oeix"], ["oeixi"], ["oïm"], ["oïu"], ["oeixin"]],
        ),
    ],
)
def test_inflector_ca_conjugate_mood_tense(
    cg, infinitive, mood, tense, expected_result
):
    tc = cg.conjugate_mood_tense(infinitive, mood, tense)
    assert [list(c) for c in tc] == expected_result


def test_inflector_ca_conjugate_simple_past(cg):
    cc = cg.conjugate_mood_tense(
        "pertànyer", Moods.ca.Indicatiu, Tenses.ca.PassatSimple
    )
    assert cc == TenseConjugation(
        Tenses.ca.PassatSimple,
        [
            Conjugation(
                Person.First,
                Number.Singular,
                None,
                "jo",
                ["jo pertanyí", "jo pertanguí"],
            ),
            Conjugation(
                Person.Second,
                Number.Singular,
                None,
                "tu",
                ["tu pertanyeres", "tu pertangueres"],
            ),
            Conjugation(
                Person.Third,
                Number.Singular,
                Gender.m,
                "ell",
                ["ell pertanyé", "ell pertangué"],
            ),
            Conjugation(
                Person.Third,
                Number.Singular,
                Gender.f,
                "ella",
                ["ella pertanyé", "ella pertangué"],
            ),
            Conjugation(
                Person.First,
                Number.Plural,
                None,
                "nosaltres",
                ["nosaltres pertanyérem", "nosaltres pertanguérem"],
            ),
            Conjugation(
                Person.Second,
                Number.Plural,
                None,
                "vosaltres",
                ["vosaltres pertanyéreu", "vosaltres pertanguéreu"],
            ),
            Conjugation(
                Person.Third,
                Number.Plural,
                Gender.m,
                "ells",
                ["ells pertanyeren", "ells pertanguéren"],
            ),
            Conjugation(
                Person.Third,
                Number.Plural,
                Gender.f,
                "elles",
                ["elles pertanyeren", "elles pertanguéren"],
            ),
        ],
    )


def test_inflector_ca_get_conj_obs(cg):
    co = cg._get_conj_obs("parlar")
    assert co.verb.infinitive == "parlar"
    assert co.verb_stem == "parl"
    assert co.template.name == "cant:ar"


def test_inflector_ca_get_conj_obs_2(cg):
    co = cg._get_conj_obs("abandonar")
    assert co.verb.infinitive == "abandonar"
    assert co.verb_stem == "abandon"
    assert co.template.name == "cant:ar"


def test_inflector_ca_get_conj_obs_3(cg):
    co = cg._get_conj_obs("pertànyer")
    assert co.verb.infinitive == "pertànyer"
    assert co.verb_stem == "pertàny"
    assert co.template.name == "pertàny:er"
    assert co.template.modify_stem == "strip-accents"


def test_inflector_ca_get_verb_stem_from_template_name(cg):
    verb_stem = cg._inflector.get_verb_stem_from_template_name("parlar", "cant:ar")
    assert verb_stem == "parl"


def test_inflector_ca_get_verb_stem_from_template_name_2(cg):
    verb_stem = cg._inflector.get_verb_stem_from_template_name("abandonar", "cant:ar")
    assert verb_stem == "abandon"


def test_inflector_ca_conjugate_simple_mood_tense(cg):
    mood = Moods.ca.Indicatiu
    tense = Tenses.ca.Present
    verb_stem = "parl"
    tense_elem = etree.fromstring(
        """<present>
            <p><i>o</i></p>
            <p><i>es</i></p>
            <p><i>a</i></p>
            <p><i>em</i></p>
            <p><i>eu</i></p>
            <p><i>en</i></p>
        </present>""",
        parser=None,
    )
    tense_template = TenseTemplateParser(Lang.ca, mood).parse(tense_elem)
    tc = cg._conjugate_simple_mood_tense(verb_stem, mood, tense, tense_template)
    assert [c.get_conjugations() for c in tc] == [
        ["jo parlo"],
        ["tu parles"],
        ["ell parla"],
        ["ella parla"],
        ["nosaltres parlem"],
        ["vosaltres parleu"],
        ["ells parlen"],
        ["elles parlen"],
    ]


@pytest.mark.parametrize(
    "person,number,gender,is_reflexive,expected_result",
    [
        (Person.First, Number.Singular, Gender.m, False, "jo"),
        (Person.First, Number.Singular, Gender.m, True, "jo me"),
        (Person.Second, Number.Singular, Gender.m, False, "tu"),
        (Person.Second, Number.Singular, Gender.m, True, "tu te"),
        (Person.Third, Number.Singular, Gender.m, False, "ell"),
        (Person.Third, Number.Singular, Gender.m, True, "ell se"),
        (Person.Third, Number.Singular, Gender.f, False, "ella"),
        (Person.Third, Number.Singular, Gender.f, True, "ella se"),
        (Person.First, Number.Plural, Gender.m, False, "nosaltres"),
        (Person.First, Number.Plural, Gender.m, True, "nosaltres nos"),
        (Person.Second, Number.Plural, Gender.m, False, "vosaltres"),
        (Person.Second, Number.Plural, Gender.m, True, "vosaltres os"),
        (Person.Third, Number.Plural, Gender.m, False, "ells"),
        (Person.Third, Number.Plural, Gender.m, True, "ells se"),
        (Person.Third, Number.Plural, Gender.f, False, "elles"),
        (Person.Third, Number.Plural, Gender.f, True, "elles se"),
    ],
)
def test_inflector_ca_get_pronouns(
    cg,
    person: Person,
    number: Number,
    gender: Gender,
    is_reflexive: bool,
    expected_result: str,
):
    pronoun = cg._inflector.get_pronouns(person, number, gender)[0]
    if is_reflexive:
        pronoun = cg._inflector.make_pronoun_reflexive(pronoun)
    assert pronoun == expected_result


def test_inflector_ca_conjugate_ser(cg):
    cc = cg.conjugate("ser")
    EXPECTED_RESULT = {
        "moods": {
            Moods.ca.Condicional: {
                "present": [
                    ["1", "s", None, "jo", ["jo seria", "jo fora"]],
                    ["2", "s", None, "tu", ["tu series", "tu fores"]],
                    ["3", "s", "m", "ell", ["ell seria", "ell fora"]],
                    ["3", "s", "f", "ella", ["ella seria", "ella fora"]],
                    [
                        "1",
                        "p",
                        None,
                        "nosaltres",
                        ["nosaltres seríem", "nosaltres fórem"],
                    ],
                    [
                        "2",
                        "p",
                        None,
                        "vosaltres",
                        ["vosaltres seríeu", "vosaltres fóreu"],
                    ],
                    ["3", "p", "m", "ells", ["ells serien", "ells foren"]],
                    ["3", "p", "f", "elles", ["elles serien", "elles foren"]],
                ]
            },
            "gerundi": {"gerundi": [["1", "s", None, "jo", ["sent", "essent"]]]},
            "imperatiu": {
                "imperatiu-present": [
                    ["2", "s", None, "tu", ["sigues"]],
                    ["3", "s", "m", "ell", ["sigui"]],
                    ["3", "s", "f", "ella", ["sigui"]],
                    ["1", "p", None, "nosaltres", ["siguem"]],
                    ["2", "p", None, "vosaltres", ["sigueu"]],
                    ["3", "p", "m", "ells", ["siguin"]],
                    ["3", "p", "f", "elles", ["siguin"]],
                ]
            },
            "indicatiu": {
                Tenses.ca.Futur: [
                    ["1", "s", None, "jo", ["jo seré"]],
                    ["2", "s", None, "tu", ["tu seràs"]],
                    ["3", "s", "m", "ell", ["ell serà"]],
                    ["3", "s", "f", "ella", ["ella serà"]],
                    ["1", "p", None, "nosaltres", ["nosaltres serem"]],
                    ["2", "p", None, "vosaltres", ["vosaltres sereu"]],
                    ["3", "p", "m", "ells", ["ells seran"]],
                    ["3", "p", "f", "elles", ["elles seran"]],
                ],
                Tenses.ca.Imperfet: [
                    ["1", "s", None, "jo", ["jo era"]],
                    ["2", "s", None, "tu", ["tu eres"]],
                    ["3", "s", "m", "ell", ["ell era"]],
                    ["3", "s", "f", "ella", ["ella era"]],
                    ["1", "p", None, "nosaltres", ["nosaltres érem"]],
                    ["2", "p", None, "vosaltres", ["vosaltres éreu"]],
                    ["3", "p", "m", "ells", ["ells eren"]],
                    ["3", "p", "f", "elles", ["elles eren"]],
                ],
                Tenses.ca.PassatSimple: [
                    ["1", "s", None, "jo", ["jo fui"]],
                    ["2", "s", None, "tu", ["tu fores"]],
                    ["3", "s", "m", "ell", ["ell fou"]],
                    ["3", "s", "f", "ella", ["ella fou"]],
                    ["1", "p", None, "nosaltres", ["nosaltres fórem"]],
                    ["2", "p", None, "vosaltres", ["vosaltres fóreu"]],
                    ["3", "p", "m", "ells", ["ells foren"]],
                    ["3", "p", "f", "elles", ["elles foren"]],
                ],
                "present": [
                    ["1", "s", None, "jo", ["jo sóc"]],
                    ["2", "s", None, "tu", ["tu ets"]],
                    ["3", "s", "m", "ell", ["ell és"]],
                    ["3", "s", "f", "ella", ["ella és"]],
                    ["1", "p", None, "nosaltres", ["nosaltres som"]],
                    ["2", "p", None, "vosaltres", ["vosaltres sou"]],
                    ["3", "p", "m", "ells", ["ells són"]],
                    ["3", "p", "f", "elles", ["elles són"]],
                ],
            },
            "infinitiu": {
                "infinitiu-present": [["1", "s", None, "jo", ["ser", "ésser"]]]
            },
            Moods.ca.Participi: {
                Tenses.ca.Participi: [
                    [None, "s", "m", None, ["estat", "sigut"]],
                    [None, "p", "m", None, ["estada", "siguda"]],
                    [None, "s", "f", None, ["estats", "siguts"]],
                    [None, "p", "f", None, ["estades", "sigudes"]],
                ]
            },
            Moods.ca.Subjuntiu: {
                Tenses.ca.Imperfet: [
                    ["1", "s", None, "jo", ["jo fos"]],
                    ["2", "s", None, "tu", ["tu fossis"]],
                    ["3", "s", "m", "ell", ["ell fos"]],
                    ["3", "s", "f", "ella", ["ella fos"]],
                    ["1", "p", None, "nosaltres", ["nosaltres fóssim"]],
                    ["2", "p", None, "vosaltres", ["vosaltres fóssiu"]],
                    ["3", "p", "m", "ells", ["ells fossin"]],
                    ["3", "p", "f", "elles", ["elles fossin"]],
                ],
                "present": [
                    ["1", "s", None, "jo", ["jo sigui"]],
                    ["2", "s", None, "tu", ["tu siguis"]],
                    ["3", "s", "m", "ell", ["ell sigui"]],
                    ["3", "s", "f", "ella", ["ella sigui"]],
                    ["1", "p", None, "nosaltres", ["nosaltres siguem"]],
                    ["2", "p", None, "vosaltres", ["vosaltres sigueu"]],
                    ["3", "p", "m", "ells", ["ells siguin"]],
                    ["3", "p", "f", "elles", ["elles siguin"]],
                ],
            },
        },
        "verb": {
            "infinitive": "ser",
            "lang": "ca",
            "pred_score": 1.0,
            "predicted": False,
            "stem": "",
            "template": "és:ser",
            "translation_en": "be",
        },
    }

    assert_json_str_equal(str(cc), json.dumps(EXPECTED_RESULT))


def test_inflector_conjugate_noconjpronouns(cg):
    cc = cg.conjugate("ser", conjugate_pronouns=False)
    expected_resp = {
        "moods": {
            Moods.ca.Condicional: {
                "present": [
                    ["1", "s", None, "jo", ["seria", "fora"]],
                    ["2", "s", None, "tu", ["series", "fores"]],
                    ["3", "s", "m", "ell", ["seria", "fora"]],
                    ["3", "s", "f", "ella", ["seria", "fora"]],
                    ["1", "p", None, "nosaltres", ["seríem", "fórem"]],
                    ["2", "p", None, "vosaltres", ["seríeu", "fóreu"]],
                    ["3", "p", "m", "ells", ["serien", "foren"]],
                    ["3", "p", "f", "elles", ["serien", "foren"]],
                ]
            },
            "gerundi": {"gerundi": [["1", "s", None, "jo", ["sent", "essent"]]]},
            "imperatiu": {
                "imperatiu-present": [
                    ["2", "s", None, "tu", ["sigues"]],
                    ["3", "s", "m", "ell", ["sigui"]],
                    ["3", "s", "f", "ella", ["sigui"]],
                    ["1", "p", None, "nosaltres", ["siguem"]],
                    ["2", "p", None, "vosaltres", ["sigueu"]],
                    ["3", "p", "m", "ells", ["siguin"]],
                    ["3", "p", "f", "elles", ["siguin"]],
                ]
            },
            "indicatiu": {
                Tenses.ca.Futur: [
                    ["1", "s", None, "jo", ["seré"]],
                    ["2", "s", None, "tu", ["seràs"]],
                    ["3", "s", "m", "ell", ["serà"]],
                    ["3", "s", "f", "ella", ["serà"]],
                    ["1", "p", None, "nosaltres", ["serem"]],
                    ["2", "p", None, "vosaltres", ["sereu"]],
                    ["3", "p", "m", "ells", ["seran"]],
                    ["3", "p", "f", "elles", ["seran"]],
                ],
                Tenses.ca.Imperfet: [
                    ["1", "s", None, "jo", ["era"]],
                    ["2", "s", None, "tu", ["eres"]],
                    ["3", "s", "m", "ell", ["era"]],
                    ["3", "s", "f", "ella", ["era"]],
                    ["1", "p", None, "nosaltres", ["érem"]],
                    ["2", "p", None, "vosaltres", ["éreu"]],
                    ["3", "p", "m", "ells", ["eren"]],
                    ["3", "p", "f", "elles", ["eren"]],
                ],
                Tenses.ca.PassatSimple: [
                    ["1", "s", None, "jo", ["fui"]],
                    ["2", "s", None, "tu", ["fores"]],
                    ["3", "s", "m", "ell", ["fou"]],
                    ["3", "s", "f", "ella", ["fou"]],
                    ["1", "p", None, "nosaltres", ["fórem"]],
                    ["2", "p", None, "vosaltres", ["fóreu"]],
                    ["3", "p", "m", "ells", ["foren"]],
                    ["3", "p", "f", "elles", ["foren"]],
                ],
                "present": [
                    ["1", "s", None, "jo", ["sóc"]],
                    ["2", "s", None, "tu", ["ets"]],
                    ["3", "s", "m", "ell", ["és"]],
                    ["3", "s", "f", "ella", ["és"]],
                    ["1", "p", None, "nosaltres", ["som"]],
                    ["2", "p", None, "vosaltres", ["sou"]],
                    ["3", "p", "m", "ells", ["són"]],
                    ["3", "p", "f", "elles", ["són"]],
                ],
            },
            "infinitiu": {
                "infinitiu-present": [["1", "s", None, "jo", ["ser", "ésser"]]]
            },
            Tenses.ca.Participi: {
                Tenses.ca.Participi: [
                    [None, "s", "m", None, ["estat", "sigut"]],
                    [None, "p", "m", None, ["estada", "siguda"]],
                    [None, "s", "f", None, ["estats", "siguts"]],
                    [None, "p", "f", None, ["estades", "sigudes"]],
                ]
            },
            Moods.ca.Subjuntiu: {
                Tenses.ca.Imperfet: [
                    ["1", "s", None, "jo", ["fos"]],
                    ["2", "s", None, "tu", ["fossis"]],
                    ["3", "s", "m", "ell", ["fos"]],
                    ["3", "s", "f", "ella", ["fos"]],
                    ["1", "p", None, "nosaltres", ["fóssim"]],
                    ["2", "p", None, "vosaltres", ["fóssiu"]],
                    ["3", "p", "m", "ells", ["fossin"]],
                    ["3", "p", "f", "elles", ["fossin"]],
                ],
                "present": [
                    ["1", "s", None, "jo", ["sigui"]],
                    ["2", "s", None, "tu", ["siguis"]],
                    ["3", "s", "m", "ell", ["sigui"]],
                    ["3", "s", "f", "ella", ["sigui"]],
                    ["1", "p", None, "nosaltres", ["siguem"]],
                    ["2", "p", None, "vosaltres", ["sigueu"]],
                    ["3", "p", "m", "ells", ["siguin"]],
                    ["3", "p", "f", "elles", ["siguin"]],
                ],
            },
        },
        "verb": {
            "infinitive": "ser",
            "lang": "ca",
            "pred_score": 1.0,
            "predicted": False,
            "stem": "",
            "template": "és:ser",
            "translation_en": "be",
        },
    }
    assert_json_str_equal(str(cc), json.dumps(expected_resp))
