from .conjugator_error import ConjugatorError  # type: ignore
from .conjugations_parser_error import ConjugationsParserError  # type: ignore
from .conjugation_template_error import ConjugationTemplateError  # type: ignore
from .invalid_lang_error import InvalidLangError  # type: ignore
from .invalid_mood_error import InvalidMoodError  # type: ignore
from .invalid_tense_error import InvalidTenseError  # type: ignore
from .template_not_found_error import TemplateNotFoundError  # type: ignore
from .verb_not_found_error import VerbNotFoundError  # type: ignore
from .verbs_parser_error import VerbsParserError  # type: ignore