version: 1
formatters:
  simpleFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailedFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simpleFormatter
    stream: ext://sys.stdout
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simpleFormatter
    filename: verbecc.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  verbecc:
    level: CRITICAL
    handlers: [consoleHandler, fileHandler]
    propagate: False
root:
  level: CRITICAL
  handlers: [consoleHandler]