version: 1
ENABLE_ML_PREDICTION: true
JSBEAUTIFIER_ENABLE: true
JSBEAUTIFIER_OPTS:
  brace_style: expand
  break_chained_methods: false
  comma_first: false
  e4x: false
  end_with_newline: false
  indent_char: " "
  indent_empty_lines: false
  indent_inner_html: false
  indent_scripts: normal
  indent_size: 4
  jslint_happy: false
  keep_array_indentation: false
  max_preserve_newlines: -1
  preserve_newlines: false
  space_before_conditional: true
  unescape_strings: false
  wrap_line_length: 80
JSON_OPTS:
  allow_nan: false
  sort_keys: true
  ensure_ascii: true
  indent: 4
