from verbecc.src.defs.types.pronoun.pronoun import Pronoun
from verbecc.src.defs.types.pronoun.pronouns import Pronouns
from verbecc.src.defs.types.pronoun.pronoun_factory import PronounFactory
from verbecc.src.defs.types.pronoun.lang.pronoun_ca import PronounCa
from verbecc.src.defs.types.pronoun.lang.pronoun_en import PronounEn
from verbecc.src.defs.types.pronoun.lang.pronoun_es import PronounEs
from verbecc.src.defs.types.pronoun.lang.pronoun_fr import PronounFr
from verbecc.src.defs.types.pronoun.lang.pronoun_it import PronounIt
from verbecc.src.defs.types.pronoun.lang.pronoun_pt import PronounPt
from verbecc.src.defs.types.pronoun.lang.pronoun_ro import PronounRo
